version: 2
updates:
- package-ecosystem: npm
  directory: "/uaa"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/k8s"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/statsd"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-name: "org.springframework.boot:*"
  - dependency-name: "org.apache.tomcat:*"
  ignore:
  - dependency-name: "org.apache.tomcat:*"
    update-types: ["version-update:semver-major"] # Stay in Tomcat major version and do updates manually, based on Spring Boot version.
  - dependency-name: org.flywaydb:flyway-core
    versions:
    - ">= 8" # Version 8+ no longer supports MySQL 5.7, we're not ready to drop MySQL 5.7 support yet. Tracker story: https://www.pivotaltracker.com/story/show/180879913.
- package-ecosystem: gradle
  directory: "/model"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/metrics-data"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
- package-ecosystem: gradle
  directory: "/server"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
