name: Java CI with Gradle

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# Run job on CF landscape, e.g. ubuntu 1804 and bellsoft java 21
permissions:
  contents: read

jobs:
  uaa_standalone_test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        java: [ '21' ]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - run: ./gradlew --no-daemon -Dspring.profiles.active=hsqldb -DfailOnPassedAfterRetry=false --no-daemon test
